### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by miguilimzero** [michailowski/Teeditor#5]
Would it be possible to add linux support?

**Comment by michailowski** [comment]
Hi! Universal Windows Platform ([UWP](http://blogs.windows.com/buildingapps/2015/03/02/a-first-look-at-the-windows-10-universal-app-platform/)) core APIs (also known as Windows Runtime / WinRT) and the resulting [APPX](https://msdn.microsoft.com/en-us/library/windows/apps/dn726767.aspx?f=255&MSPPError=-2147217396) based applications only target Windows 10 platforms (Phone, PC, Tablet...) as those APIs and runtime do not exist on the other desktops.

So, in the form in which the editor currently exists - **no**. 

I understand that this is sad for many people, but the development and release of this editor depended on it. I couldn't have implemented a lot of the UI stuff on my own. The .NET platform in the form of UWP allowed me to implement this. It's a colossal undertaking that wouldn't have made sense. As such, I chose what was closest to me, what I had worked with before. 

Just so you understand more - the display of the map in the window is done by the graphics processor through calls to the DirectX 11 API. But there are also a lot of UI elements in there that are rendered by UWP's internal mechanisms and additional frameworks. These are independent of what is displayed with DirectX 11. At least in a direct sense, as far as I know.

Perhaps someone would have the courage to invent this editor entirely using DirectX features, but it seems pointless and increases development complexity manifold.
